resizeimg_cir = cv2.resize(img_cir, (200, 499))
# resizeimg_rect_gray = cv2.cvtColor(img_rect, cv2.COLOR_BGR2GRAY)
# resizeimg_cir_gray = cv2.cvtColor(img_cir, cv2.COLOR_BGR2GRAY)
# and_gray = cv2.bitwise_and(resizeimg_rect_gray, resizeimg_cir_gray, mask=None)
# or_gray = cv2.bitwise_or(resizeimg_rect_gray, resizeimg_cir_gray, mask=None)
# xor_gray = cv2.bitwise_xor(resizeimg_rect_gray, resizeimg_cir_gray, mask=None)
# cv2.imshow("show gray merged ground",and_gray)
# cv2.imshow("show gray merged or",or_gray)
# cv2.imshow("show gray merged xor",xor_gray)
# cv2.waitKey(0)
# cv2.destroyAllWindows()
# img_bgr = cv2.imread("review_opencv/images/rectangle.jpg", 1)
# img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
